server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demorestfulapi
    username: postgres
    password: 19932009
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true